# Generated by Django 4.0.2 on 2022-03-17 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'зарплатный проект',
                'verbose_name_plural': 'зарплатные проекты',
                'db_table': 'salary_project',
            },
        ),
        migrations.CreateModel(
            name='ClientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visit', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('first_name_client', models.CharField(max_length=150, verbose_name='фамилия клиента')),
                ('middle_name_client', models.CharField(max_length=150, verbose_name='отчество клиента')),
                ('last_name_client', models.CharField(max_length=150, verbose_name='фамилия клиента')),
                ('date_of_birth', models.CharField(max_length=10, verbose_name='дата рождения клиента')),
                ('inn_employer', models.IntegerField(verbose_name='инн работодателя')),
                ('salary_bank', models.CharField(choices=[('ВТБ', 'ВТБ'), ('Сбербанк', 'Сбербанк'), ('СГБ', 'СГБ'), ('ПочтаБанк', 'ПочтаБанк'), ('Тинькофф', 'Тинькофф'), ('Альфа', 'Альфа'), ('Наличка', 'Наличка'), ('Другой', 'Другой'), ('Нет', 'Нет')], default='Другой', max_length=50, verbose_name='зарплатный банк')),
                ('pension_bank', models.CharField(choices=[('ВТБ', 'ВТБ'), ('Сбербанк', 'Сбербанк'), ('СГБ', 'СГБ'), ('ПочтаБанк', 'ПочтаБанк'), ('Тинькофф', 'Тинькофф'), ('Альфа', 'Альфа'), ('Наличка', 'Наличка'), ('Другой', 'Другой'), ('Нет', 'Нет')], default='Нет', max_length=50, verbose_name='пенсионный банк')),
                ('main_product', models.CharField(choices=[('Кредит наличными', 'Кредит наличными'), ('Кредитная карта', 'Кредитная карта'), ('Депозит', 'Депозит'), ('Зарплатная карта', 'Зарплатная карта'), ('Пакет услуг', 'Пакет услуг'), ('Сервис', 'Сервис')], max_length=50, verbose_name='продукт')),
                ('credit_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='кн результат')),
                ('credit_sum', models.IntegerField(verbose_name='кн сумма')),
                ('credit_comment', models.TextField(verbose_name='кн комментарии')),
                ('credit_insurance_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='фз кн результат')),
                ('credit_insurance_sum', models.IntegerField(verbose_name='фз кн сумма')),
                ('credit_insurance_comment', models.TextField(verbose_name='фз кн комментарии')),
                ('credit_card_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='кк результат')),
                ('credit_card_comment', models.TextField(verbose_name='кк комментарии')),
                ('credit_card_insurance_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='фз кк результат')),
                ('credit_card_insurance_comment', models.TextField(verbose_name='фз кк комментарии')),
                ('deposit_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='депозит результат')),
                ('deposit_sum', models.IntegerField(verbose_name='депозит сумма')),
                ('deposit_comment', models.TextField(verbose_name='депозит комментарии')),
                ('service_package_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='пу результат')),
                ('service_package_comment', models.TextField(verbose_name='пу комментарии')),
                ('izp_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='изп результат')),
                ('izp_comment', models.TextField(verbose_name='изп комментарии')),
                ('pension_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='перевод пенсии результат')),
                ('pension_comment', models.TextField(verbose_name='перевод пенсии комментарии')),
                ('ksp_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='ксп результат')),
                ('ksp_sum', models.IntegerField(verbose_name='ксп сумма')),
                ('ksp_comment', models.TextField(verbose_name='ксп комментарии')),
                ('nsg_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='нсж результат')),
                ('nsg_sum', models.IntegerField(verbose_name='нсж сумма')),
                ('nsg_comment', models.TextField(verbose_name='нсж комментарии')),
                ('isg_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='исж результат')),
                ('isg_sum', models.IntegerField(verbose_name='исж сумма')),
                ('isg_comment', models.TextField(verbose_name='исж комментарии')),
                ('npo_result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='нпо результат')),
                ('npo_sum', models.IntegerField(verbose_name='нпо сумма')),
                ('npo_comment', models.TextField(verbose_name='нпо комментарии')),
                ('date_next_contact', models.DateField(verbose_name='дата следующего контакта')),
                ('total_comment', models.TextField(verbose_name='итоговые комментарии')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_visit', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'визит клиента',
                'verbose_name_plural': 'визиты клиентов',
                'db_table': 'client_visit',
                'ordering': ['-date_visit'],
            },
        ),
        migrations.CreateModel(
            name='ClientCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_call', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('first_name_client', models.CharField(max_length=150, verbose_name='фамилия клиента')),
                ('middle_name_client', models.CharField(blank=True, max_length=150, verbose_name='отчество клиента')),
                ('last_name_client', models.CharField(blank=True, max_length=150, verbose_name='фамилия клиента')),
                ('date_of_birth', models.CharField(blank=True, max_length=10, verbose_name='дата рождения клиента')),
                ('main_product', models.CharField(choices=[('Кредит наличными', 'Кредит наличными'), ('Кредитная карта', 'Кредитная карта'), ('Депозит', 'Депозит'), ('Зарплатная карта', 'Зарплатная карта'), ('Пакет услуг', 'Пакет услуг'), ('Сервис', 'Сервис')], max_length=50, verbose_name='продукт')),
                ('result', models.CharField(choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='результат звонка')),
                ('sum', models.IntegerField(verbose_name='сумма')),
                ('comment', models.TextField(verbose_name='комментарии')),
                ('date_next_contact', models.DateField(verbose_name='дата следующего контакта')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_call', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'звонок клиенту',
                'verbose_name_plural': 'звонки клиентам',
                'db_table': 'client_call',
                'ordering': ['-date_call'],
            },
        ),
    ]
