# Generated by Django 4.0.2 on 2022-03-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit', '0002_alter_clientcall_first_name_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcall',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарии'),
        ),
        migrations.AlterField(
            model_name='clientcall',
            name='date_next_contact',
            field=models.DateField(blank=True, verbose_name='дата следующего контакта'),
        ),
        migrations.AlterField(
            model_name='clientcall',
            name='sum',
            field=models.IntegerField(blank=True, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_card_comment',
            field=models.TextField(blank=True, verbose_name='кк комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_card_insurance_comment',
            field=models.TextField(blank=True, verbose_name='фз кк комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_card_insurance_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='фз кк результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_card_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='кк результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_comment',
            field=models.TextField(blank=True, verbose_name='кн комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_insurance_comment',
            field=models.TextField(blank=True, verbose_name='фз кн комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_insurance_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='фз кн результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_insurance_sum',
            field=models.IntegerField(blank=True, verbose_name='фз кн сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='кн результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_sum',
            field=models.IntegerField(blank=True, verbose_name='кн сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='date_next_contact',
            field=models.DateField(blank=True, verbose_name='дата следующего контакта'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='deposit_comment',
            field=models.TextField(blank=True, verbose_name='депозит комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='deposit_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='депозит результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='deposit_sum',
            field=models.IntegerField(blank=True, verbose_name='депозит сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='inn_employer',
            field=models.IntegerField(blank=True, verbose_name='инн работодателя'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='isg_comment',
            field=models.TextField(blank=True, verbose_name='исж комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='isg_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='исж результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='isg_sum',
            field=models.IntegerField(blank=True, verbose_name='исж сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='izp_comment',
            field=models.TextField(blank=True, verbose_name='изп комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='izp_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='изп результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='ksp_comment',
            field=models.TextField(blank=True, verbose_name='ксп комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='ksp_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='ксп результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='ksp_sum',
            field=models.IntegerField(blank=True, verbose_name='ксп сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='npo_comment',
            field=models.TextField(blank=True, verbose_name='нпо комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='npo_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='нпо результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='npo_sum',
            field=models.IntegerField(blank=True, verbose_name='нпо сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='nsg_comment',
            field=models.TextField(blank=True, verbose_name='нсж комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='nsg_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='нсж результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='nsg_sum',
            field=models.IntegerField(blank=True, verbose_name='нсж сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='pension_comment',
            field=models.TextField(blank=True, verbose_name='перевод пенсии комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='pension_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='перевод пенсии результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='service_package_comment',
            field=models.TextField(blank=True, verbose_name='пу комментарии'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='service_package_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='пу результат'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='total_comment',
            field=models.TextField(blank=True, verbose_name='итоговые комментарии'),
        ),
    ]
