# Generated by Django 4.0.2 on 2022-03-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit', '0003_alter_clientcall_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcall',
            name='sum',
            field=models.IntegerField(default=0, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_insurance_sum',
            field=models.IntegerField(default=0, verbose_name='фз кн сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='credit_sum',
            field=models.IntegerField(default=0, verbose_name='кн сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='deposit_sum',
            field=models.IntegerField(default=0, verbose_name='депозит сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='isg_sum',
            field=models.IntegerField(default=0, verbose_name='исж сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='ksp_sum',
            field=models.IntegerField(default=0, verbose_name='ксп сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='npo_sum',
            field=models.IntegerField(default=0, verbose_name='нпо сумма'),
        ),
        migrations.AlterField(
            model_name='clientvisit',
            name='nsg_sum',
            field=models.IntegerField(default=0, verbose_name='нсж сумма'),
        ),
    ]
