# Generated by Django 4.0.2 on 2022-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit', '0004_alter_clientcall_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='inn_employer',
            field=models.IntegerField(blank=True, null=None, verbose_name='инн работодателя'),
        ),
    ]
