# Generated by Django 4.0.2 on 2022-03-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit', '0006_alter_clientvisit_date_next_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='inn_employer',
            field=models.IntegerField(blank=True, default=0, verbose_name='инн работодателя'),
        ),
    ]
