# Generated by Django 4.0.2 on 2022-03-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit', '0007_alter_clientvisit_inn_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisit',
            name='date_next_contact',
            field=models.DateField(blank=True, null=True, verbose_name='дата следующего контакта'),
        ),
    ]
