# Generated by Django 4.0.2 on 2022-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit', '0008_alter_clientvisit_date_next_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisit',
            name='type_next_contact',
            field=models.CharField(blank=True, choices=[('Звонок', 'Звонок'), ('Визит', 'Визит')], max_length=50, verbose_name='тип следующего контакта'),
        ),
    ]
