# Generated by Django 4.0.2 on 2022-03-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit', '0010_clientcall_type_next_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisit',
            name='broker_navigate_comment',
            field=models.TextField(blank=True, verbose_name='лиды БО комментарии'),
        ),
        migrations.AddField(
            model_name='clientvisit',
            name='broker_navigate_result',
            field=models.CharField(blank=True, choices=[('Оформлено', 'Оформлено'), ('Думает', 'Думает'), ('Отказ', 'Отказ'), ('Уже есть', 'Уже есть'), ('Планирует оформить', 'Планирует оформить'), ('', '')], max_length=50, verbose_name='лиды БО'),
        ),
        migrations.AddField(
            model_name='clientvisit',
            name='service_package_type',
            field=models.CharField(blank=True, choices=[('Мультикарта', 'Мультикарта'), ('Привилегия', 'Привилегия')], max_length=50, verbose_name='тип пу'),
        ),
    ]
