# Generated by Django 4.0.2 on 2022-03-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit', '0011_clientvisit_broker_navigate_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcall',
            name='date_next_contact',
            field=models.DateField(blank=True, null=True, verbose_name='дата следующего контакта'),
        ),
    ]
