# Generated by Django 4.0.2 on 2022-03-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.IntegerField(verbose_name='ИНН организации')),
            ],
            options={
                'verbose_name': 'инн организации',
                'verbose_name_plural': 'инн организаций',
                'db_table': 'salary_projects',
            },
        ),
    ]
